name: 'shipstation'

config-version: 2
version: '1.0'
require-dbt-version: ">=1.0.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: 
    - "target"
    - "dbt_packages"
test-paths: ["tests"]

profile: lacolombe-dtc

models:
  shipstation:
      materialized: ephemeral