name: 'shipstation'

config-version: 2
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]

profile: lacolombe-dtc

models:
  shipstation:
      materialized: ephemeral